spring:
  application:
    name: money-transfer-system

  # Default to mysql profile.
  # Override with: --spring.profiles.active=h2  (for lo    username: h2t MySQL)
  profiles:
    active: h2

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  file:
    name: logs/money-transfer-system.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  level:
    com.banking.transfer: INFO
    org.springframework.security: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
